### ISSUE TITLE
Need to use `jwks-utils` instead of `jws-jwk`

### ISSUE THREAD

**Issue by awlayton** [OADA/oada-id-client-js#15]
@abalmos Had to go and figure out that the magic in `jws-jwk` was too lame (oada/node-jws-jwk#1). I will need to make use of [jwks-utils](https://github.com/OADA/node-jwks-utils) and `jsonwebtoken`'s new JOSE header support (auth0/node-jsonwebtoken#25) instead.

**Comment by abalmos** [comment]
Chop chop
