### ISSUE TITLE
Missing return on line 40 of core.js

### ISSUE THREAD

**Issue by aultac** [OADA/oada-id-client-js#18]
Looks like callback will be called twice if it ever gets inside that if statement because it will go on executing the rest of the function.  Line 40 of core.js.

**Comment by awlayton** [comment]
Why didn't you just click edit and make a pull request of it?

**Comment by aultac** [comment]
because you're the author, I've only seen 4 lines of that file for a total of about 3 minutes, so I wanted to make sure I wasn't missing something :).

**Comment by awlayton** [comment]
That's the purpose of a pull request. Then I, the author, can check it before merging.

**Comment by aultac** [comment]
Hmmm...you make an excellent point.  Lesson learned :)
