### ISSUE TITLE
Update to use new client registration scheme

### ISSUE THREAD

**Issue by awlayton** [OADA/oada-id-client-js#25]
It needs these changes:
- [x] [Take software statement parameter](https://tools.ietf.org/html/draft-ietf-oauth-dyn-reg#section-2.3)
- [x] [Make dynamic registration request](https://tools.ietf.org/html/draft-ietf-oauth-dyn-reg#section-3.1)
- [x] [Use jwt-bearer query parameters](https://tools.ietf.org/html/draft-ietf-oauth-jwt-bearer#section-2.2)
- [x] [In client secret jwt, change `ac` to `jti`](https://tools.ietf.org/html/draft-ietf-oauth-jwt-bearer#section-3)

Tell me if I forgot anything @abalmos.

**Comment by abalmos** [comment]
Looks right to me

**Comment by awlayton** [comment]
Realized the client secret item is not actually applicable to this repo.
I addressed it in OADA/oada-client-secret#6.

**Comment by awlayton** [comment]
I think this is done, but we should write the other side and test them before merging.

**Comment by abalmos** [comment]
We need to replace oada-client-secret with jwt-bearer-client-auth

**Comment by awlayton** [comment]
This is done and merged into master.
